name: Secrets Example

on:
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Test Secret
        run: |
           echo "Masked secret:"
           echo ${{ secrets.TEST_SECRET }}
           echo "Secret :"
           echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g'